<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.9"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.2" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.9">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Services\" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="publish\publish\web.config" />
      <_ContentIncludedByDefault Remove="publish\web.config" />
      <_ContentIncludedByDefault Remove="publish\appsettings.Development.json" />
      <_ContentIncludedByDefault Remove="publish\appsettings.Example.json" />
      <_ContentIncludedByDefault Remove="publish\appsettings.json" />
      <_ContentIncludedByDefault Remove="publish\publish\appsettings.Development.json" />
      <_ContentIncludedByDefault Remove="publish\publish\appsettings.Example.json" />
      <_ContentIncludedByDefault Remove="publish\publish\appsettings.json" />
      <_ContentIncludedByDefault Remove="publish\publish\ShelfSimAPI.deps.json" />
      <_ContentIncludedByDefault Remove="publish\publish\ShelfSimAPI.runtimeconfig.json" />
      <_ContentIncludedByDefault Remove="publish\publish\ShelfSimAPI.staticwebassets.endpoints.json" />
      <_ContentIncludedByDefault Remove="publish\ShelfSimAPI.deps.json" />
      <_ContentIncludedByDefault Remove="publish\ShelfSimAPI.runtimeconfig.json" />
      <_ContentIncludedByDefault Remove="publish\ShelfSimAPI.staticwebassets.endpoints.json" />
    </ItemGroup>

</Project>
