// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShelfSimAPI.Data;

#nullable disable

namespace ShelfSimAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260103171113_RenameToWMS")]
    partial class RenameToWMS
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShelfSimAPI.Models.EnvironmentConfig", b =>
                {
                    b.Property<string>("ConfigKey")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("BoolValue")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<float>("TargetValue")
                        .HasColumnType("real");

                    b.Property<float>("Tolerance")
                        .HasColumnType("real");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ConfigKey");

                    b.ToTable("EnvironmentConfigs");
                });

            modelBuilder.Entity("ShelfSimAPI.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CellCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("EndTs")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FailReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<float?>("HandleTimeSec")
                        .HasColumnType("real");

                    b.Property<string>("MaterialName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("PathLengthCells")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Result")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RobotName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("RunId")
                        .HasColumnType("integer");

                    b.Property<float?>("SnapshotHumid")
                        .HasColumnType("real");

                    b.Property<bool?>("SnapshotLightLeak")
                        .HasColumnType("boolean");

                    b.Property<float?>("SnapshotTemp")
                        .HasColumnType("real");

                    b.Property<DateTime?>("StartTs")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float?>("TotalTimeSec")
                        .HasColumnType("real");

                    b.Property<float?>("TravelTimeSec")
                        .HasColumnType("real");

                    b.Property<string>("WorkerId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "CellCode");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("ShelfSimAPI.Models.Layout", b =>
                {
                    b.Property<string>("LayoutId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("CellCount")
                        .HasColumnType("integer");

                    b.Property<string>("CellsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GridSizeX")
                        .HasColumnType("integer");

                    b.Property<int>("GridSizeY")
                        .HasColumnType("integer");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("WarehouseX")
                        .HasColumnType("integer");

                    b.Property<int>("WarehouseY")
                        .HasColumnType("integer");

                    b.HasKey("LayoutId");

                    b.HasIndex("CreatedAt");

                    b.ToTable("Layouts");
                });

            modelBuilder.Entity("ShelfSimAPI.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LotId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("StockQty")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Vendor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("LotId");

                    b.HasIndex("Name");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("ShelfSimAPI.Models.Run", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("HandleTimeSec")
                        .HasColumnType("real");

                    b.Property<string>("LayoutId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<float>("MoveTimeoutSec")
                        .HasColumnType("real");

                    b.Property<int>("RandomSeed")
                        .HasColumnType("integer");

                    b.Property<float>("RobotSpeedCellsPerSec")
                        .HasColumnType("real");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<int>("TopN")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LayoutId");

                    b.HasIndex("Status");

                    b.ToTable("Runs");
                });

            modelBuilder.Entity("ShelfSimAPI.Models.Job", b =>
                {
                    b.HasOne("ShelfSimAPI.Models.Run", "Run")
                        .WithMany("Jobs")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("ShelfSimAPI.Models.Run", b =>
                {
                    b.Navigation("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
