name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: shelfsim
  SERVICE_NAME: shelfsim-api
  REGION: asia-northeast3
  IMAGE_NAME: asia-northeast3-docker.pkg.dev/shelfsim/shelfsim-api/app

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ env.PROJECT_ID }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Create Artifact Registry repository (if not exists)
      run: |
        gcloud artifacts repositories create shelfsim-api \
          --repository-format=docker \
          --location=asia-northeast3 \
          --description="ShelfSim API Docker images" || true

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker asia-northeast3-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build -t ${{ env.IMAGE_NAME }}:${{ github.sha }} \
                     -t ${{ env.IMAGE_NAME }}:latest .

    - name: Push Docker image to Artifact Registry
      run: |
        docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}
        docker push ${{ env.IMAGE_NAME }}:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --image ${{ env.IMAGE_NAME }}:${{ github.sha }} \
          --platform managed \
          --region ${{ env.REGION }} \
          --allow-unauthenticated \
          --set-env-vars "ConnectionStrings__DefaultConnection=${{ secrets.DATABASE_CONNECTION_STRING }}" \
          --memory 512Mi \
          --cpu 1 \
          --min-instances 0 \
          --max-instances 10

    - name: Show service URL
      run: |
        gcloud run services describe ${{ env.SERVICE_NAME }} \
          --platform managed \
          --region ${{ env.REGION }} \
          --format 'value(status.url)'