name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: shelfsim
  SERVICE_NAME: shelfsim-api
  REGION: asia-northeast3
  IMAGE_NAME: gcr.io/shelfsim/shelfsim-api

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Authenticate to Google Cloud
      env:
        GCP_SA_KEY_BASE64: ${{ secrets.GCP_SA_KEY }}
      run: |
        echo "$GCP_SA_KEY_BASE64" | base64 -d > $HOME/gcp-key.json
        gcloud auth activate-service-account --key-file=$HOME/gcp-key.json
        gcloud config set project ${{ env.PROJECT_ID }}

    - name: Configure Docker for GCR
      run: gcloud auth configure-docker

    - name: Build Docker image
      run: |
        docker build -t ${{ env.IMAGE_NAME }}:${{ github.sha }} \
                     -t ${{ env.IMAGE_NAME }}:latest .

    - name: Push Docker image to GCR
      run: |
        docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}
        docker push ${{ env.IMAGE_NAME }}:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --image ${{ env.IMAGE_NAME }}:${{ github.sha }} \
          --platform managed \
          --region ${{ env.REGION }} \
          --allow-unauthenticated \
          --set-env-vars "ConnectionStrings__DefaultConnection=${{ secrets.DATABASE_CONNECTION_STRING }}" \
          --memory 512Mi \
          --cpu 1 \
          --min-instances 0 \
          --max-instances 10

    - name: Show service URL
      run: |
        gcloud run services describe ${{ env.SERVICE_NAME }} \
          --platform managed \
          --region ${{ env.REGION }} \
          --format 'value(status.url)'